r_sho_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
l_sho_pitch:
  max_position_limit: 4095
  min_position_limit: 0
  operating_mode: 3
  position_d_gain: 0
  position_i_gain: 0
  position_p_gain: 800
  return_delay_time: 1
  shutdown: 56
